### ISSUE TITLE
First line break of text message gets ignored

### ISSUE THREAD

**Issue by maddo7** [nodemailer/mailparser#217] opened 2019-05-02 12:26 UTC
It seems the first line break for the text output is being ignored:
```
 const simpleParser = require('mailparser').simpleParser;
 var mail = `Content-Type: text/plain; charset=utf-8; format=flowed

Hello
test
123

`;

 simpleParser(mail, {}, (err, parsed) => {
	console.log(parsed);
 });
```

will output 

`text: 'Hellotest\n123\n\n',`

The first line break after Hello gets ignored.

**Comment by luddd3** [comment] 2019-05-06 15:33
I also ran into this issue. The problem is a bug within the [libmime](https://github.com/nodemailer/libmime) package, which is used by [mail-split](https://github.com/andris9/mailsplit)

@andris9 has merged a pull request with a fix, and I'm sure he will update mail-split and this repository soon.

**Closed** 2019-10-28 13:17 UTC
