### ISSUE TITLE
Performing extremely slowly on average messages

### ISSUE THREAD

**Issue by pshah123** [nodemailer/mailparser#262] opened 2020-05-05 02:07 UTC
Usually when I use Mailparser I don't run into any speed issues even with messages 10MB+ long. However recently I noticed that even 1MB emails take 5+ seconds to parse.

I tested this like so on several messages:
``` js
console.time("Parse " + body.length)
const parsed = await simpleParser(body, {
    skipHtmlToText: true,
    skipTextToHtml: true,
    maxHtmlLengthToParse: 1000 * 1000,
})
console.timeEnd("Parse " + body.length)
console.log(body.length, JSON.stringify(parsed).length)
```

Giving me:
```
Parse 525372: 3004.381ms
525372 90645

Parse 910565: 6415.893ms
910565 154485

Parse 2091666: 12697.030ms
2091666 105554

Parse 4859648: 14608.405ms
4859648 70672
```

This would indicate that even 500KB messages take 3s to parse, and a ~5MB message would take 15s. I'm fairly certain these are not normal speeds as I've gotten much faster out of mailparser in the past.

I'm running i7 quad core, 16GB RAM, and 1060X GPU.

I'm wondering if there's any way to speed this up -- for example, if there's a way to skip the attachments.

**Comment by andris9** [comment] 2020-05-05 02:17
There haven’t been any changes in Mailparser for some time by now and the parsing core itself has been unchanged for several years, so if parsing has gotten slower recently then whatever is the cause it must be external

**Comment by pshah123** [comment] 2020-05-05 02:27
Is there any way to have it skip attachment bodies? i.e. return the filename but not the content

**Comment by zackschuster** [comment] 2020-07-27 04:27
off-the-shelf profiling of the `emailjs` test code points to [this block of code in `mailsplit`](https://github.com/andris9/mailsplit/blob/master/lib/message-splitter.js#L70) being the likely culprit. for whatever reason, there's a correlation between that code interacting with large text messages & `__kernelrpc_thread_policy_set` being called thousands of times.

here's the relevant logs:
[profile.zip](https://github.com/nodemailer/mailparser/files/4979931/profile.zip)

**Comment by andris9** [comment] 2020-09-07 09:10
Probably related to some local settings, does not seem to be a general issue. Closing until additional details are known.

**Closed by andris9** 2020-09-07 09:10 UTC
