### ISSUE TITLE
TypeError: Cannot set property errored of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by gustavos00** [nodemailer/mailparser#318] opened 2022-07-18 10:43 UTC
Hello,
First of all, I don't know if this is the right place to create a issue about my problem.

Basically, I am using a dependency (_is not the nodemailer_) that use mail-parser as a dependency. When I try to use a specific event, is giving the follow error:
`.../node_modules/mailparser/lib/mail-parser.js:141`
`       this.errored = false;`
`TypeError: Cannot set property errored of #<Readable> which has only a getter`

**Comment by andris9** [comment] 2022-07-18 10:47
Is this the latest version of Mailparser?

**Comment by gustavos00** [comment] 2022-07-18 10:50
> Is this the latest version of Mailparser?

No, it's the 2.8.1 version. When I tried to update it with `npm install`, he doesn't update.

**Comment by andris9** [comment] 2022-07-18 11:03
The error is caused by Node v18 as it had a lot of breaking changes. The latest version of Mailparser is compatible with Node 18.

In general, before reporting an issue, always check that you are running the latest version, as known bugs are usually fixed in the latest.

**Closed by andris9** 2022-07-18 11:03 UTC

**Comment by yoavaviram** [comment] 2024-07-05 08:45
I am getting the above error on AWS with node v18 and mailparser v3.7.1. I'm also getting it with node v20, but not with node v16.

Any ideas @andris9 ?
